modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="blockoutlinecustomizer"
version="${version}"
displayName="Block Outline Customizer"
description='''Customize your block outline color, opacity, and width.'''
authors="Anomz"

[[dependencies.blockoutlinecustomizer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.blockoutlinecustomizer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"